name: denguescaner
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.3.0

  cupertino_icons: ^1.0.8
  camera: ^0.12.0+1
  google_ml_kit: ^0.21.0
  image: ^4.8.0
  geolocator: ^14.0.2
  firebase_storage: ^13.3.0
  path_provider: ^2.1.5
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
# Configuración del splash screen
flutter_native_splash:
  color: "#2d6a4f"
  image: assets/images/fondo dengue.png
  android: true
  ios: true

# Configuración del ícono de la app
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/fondo dengue.png"
  remove_alpha_ios: true